import {
  audioPlayerBinder,
  buttonBinder,
  cardBinder,
  checkBoxBinder,
  choicePickerBinder,
  columnBinder,
  dateTimeInputBinder,
  dividerBinder,
  iconBinder,
  imageBinder,
  listBinder,
  modalBinder,
  rowBinder,
  sliderBinder,
  tabsBinder,
  textFieldBinder,
  textBinder,
  videoBinder,
} from '@anycms/a2ui-core';
import { createAngularComponent, type AngularComponentRegistry, type AngularRegistryEntry } from './adapter/types';
import {
  AudioPlayerViewComponent,
  ButtonViewComponent,
  CardViewComponent,
  CheckBoxViewComponent,
  ChoicePickerViewComponent,
  ColumnViewComponent,
  DateTimeInputViewComponent,
  DividerViewComponent,
  IconViewComponent,
  ImageViewComponent,
  ListViewComponent,
  ModalViewComponent,
  RowViewComponent,
  SliderViewComponent,
  TabsViewComponent,
  TextFieldViewComponent,
  TextViewComponent,
  VideoViewComponent,
} from './components';

/** Basic-catalog component type -> `{ binder, view }` map. */
export const basicAngularComponents: AngularComponentRegistry = new Map<string, AngularRegistryEntry>([
  ['Text', createAngularComponent(textBinder, TextViewComponent)],
  ['Image', createAngularComponent(imageBinder, ImageViewComponent)],
  ['Icon', createAngularComponent(iconBinder, IconViewComponent)],
  ['Video', createAngularComponent(videoBinder, VideoViewComponent)],
  ['AudioPlayer', createAngularComponent(audioPlayerBinder, AudioPlayerViewComponent)],
  ['Row', createAngularComponent(rowBinder, RowViewComponent)],
  ['Column', createAngularComponent(columnBinder, ColumnViewComponent)],
  ['List', createAngularComponent(listBinder, ListViewComponent)],
  ['Card', createAngularComponent(cardBinder, CardViewComponent)],
  ['Tabs', createAngularComponent(tabsBinder, TabsViewComponent)],
  ['Divider', createAngularComponent(dividerBinder, DividerViewComponent)],
  ['Modal', createAngularComponent(modalBinder, ModalViewComponent)],
  ['Button', createAngularComponent(buttonBinder, ButtonViewComponent)],
  ['CheckBox', createAngularComponent(checkBoxBinder, CheckBoxViewComponent)],
  ['TextField', createAngularComponent(textFieldBinder, TextFieldViewComponent)],
  ['DateTimeInput', createAngularComponent(dateTimeInputBinder, DateTimeInputViewComponent)],
  ['ChoicePicker', createAngularComponent(choicePickerBinder, ChoicePickerViewComponent)],
  ['Slider', createAngularComponent(sliderBinder, SliderViewComponent)],
]);
